### ISSUE TITLE
Is it possible to download the shader code generated by Hydra?

### ISSUE THREAD

**Issue by animanoir** [ojack/hydra#148]

**Comment by zachkrall** [comment]
i'm having trouble finding the documentation but there's a `.glsl()` function that you can use instead of `.out()` to get shader code

```
shader = solid(0,0,1)
shader.out()
console.log(shader.glsl()[0].frag)
```

preview:
https://hydra.ojack.xyz/?code=c2hhZGVyJTIwJTNEJTIwc29saWQoMCUyQzAlMkMxKSUwQXNoYWRlci5vdXQoKSUwQWNvbnNvbGUubG9nKHNoYWRlci5nbHNsKCklNUIwJTVELmZyYWcpJTBBJTBBJTJGJTJGJTIwb3BlbiUyMGNvbnNvbGUlMjBpbiUyMGJyb3dzZXIlMjB0byUyMHNlZSUyMGZyYWdtZW50JTIwc2hhZGVyJTIwY29kZQ==

**Comment by animanoir** [comment]
awesome! exactly what I needed. thanks!
