### ISSUE TITLE
Impossible to find the IP address of hydra-editor.glitch.me.

### ISSUE THREAD

**Issue by damessina** [ojack/hydra#68]
Hi,
I'm trying to enter the site, but the server isn't reachable. The equivalent error is `DNS_PROBE_FINISHED_NXDOMAIN`.
I tried with Linux mint, with Windows and with several browsers but the error is the same. I know that sometimes Windows have some problems with firewalls and block the access to hydra, but I I'm not sure what to to.
It's the second time I enter the site and the first one was from a different wi-fi connection (now I'm trying with a home connection). Do you have problems with accessing hydra, too? Is it a server problem?

**Comment by ojack** [comment]
I believe this is related to the hosting at glitch.com as well as your specific internet connection/ dns configuration. I would like to find different hosting for hydra, but in the meantime will close this because it is outside the scope of this repository. Feel free to continue commenting here, however!
