### ISSUE TITLE
No extensions folder

### ISSUE THREAD

**Issue by mglavall** [ojack/hydra#93]
I was trying to install the screen-capture-extension following the Readme of the project, but there is not any of the folders mentioned:

> To install, go to chrome://extensions Click "Load unpacked extension", and select the "extensions" folder in "screen-capture-extension" in this repo. Restart chrome. The extension should work from now on without needing to reinstall.

Where can I find it?

Thank you!

**Comment by zachkrall** [comment]
I think `initScreen` should work without the extension now because hydra-synth is using `getDisplayMedia()`

This might just need to be removed from the readme.

<img width="1318" alt="Screen Shot 2020-07-13 at 4 47 19 PM" src="https://user-images.githubusercontent.com/2532937/87352141-8f31f100-c528-11ea-913b-05c20a766872.png">

**Comment by mglavall** [comment]
That's awesome! Thank you for the super fast response :)
